################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/cadical/src/lookahead.cpp \
../src/cadical/src/limit.cpp \
../src/cadical/src/flip.cpp \
../src/cadical/src/collect.cpp \
../src/cadical/src/queue.cpp \
../src/cadical/src/external.cpp \
../src/cadical/src/shrink.cpp \
../src/cadical/src/phases.cpp \
../src/cadical/src/ema.cpp \
../src/cadical/src/signal.cpp \
../src/cadical/src/cadical.cpp \
../src/cadical/src/propagate.cpp \
../src/cadical/src/logging.cpp \
../src/cadical/src/compact.cpp \
../src/cadical/src/cover.cpp \
../src/cadical/src/decompose.cpp \
../src/cadical/src/averages.cpp \
../src/cadical/src/mobical.cpp \
../src/cadical/src/resources.cpp \
../src/cadical/src/lratbuilder.cpp \
../src/cadical/src/file.cpp \
../src/cadical/src/solution.cpp \
../src/cadical/src/format.cpp \
../src/cadical/src/probe.cpp \
../src/cadical/src/terminal.cpp \
../src/cadical/src/condition.cpp \
../src/cadical/src/elim.cpp \
../src/cadical/src/ternary.cpp \
../src/cadical/src/gates.cpp \
../src/cadical/src/restore.cpp \
../src/cadical/src/lucky.cpp \
../src/cadical/src/score.cpp \
../src/cadical/src/external_propagate.cpp \
../src/cadical/src/idruptracer.cpp \
../src/cadical/src/ccadical.cpp \
../src/cadical/src/options.cpp \
../src/cadical/src/version.cpp \
../src/cadical/src/subsume.cpp \
../src/cadical/src/lratchecker.cpp \
../src/cadical/src/var.cpp \
../src/cadical/src/analyze.cpp \
../src/cadical/src/deduplicate.cpp \
../src/cadical/src/proof.cpp \
../src/cadical/src/instantiate.cpp \
../src/cadical/src/transred.cpp \
../src/cadical/src/minimize.cpp \
../src/cadical/src/arena.cpp \
../src/cadical/src/lidruptracer.cpp \
../src/cadical/src/contract.cpp \
../src/cadical/src/random.cpp \
../src/cadical/src/reduce.cpp \
../src/cadical/src/solver.cpp \
../src/cadical/src/ipasir.cpp \
../src/cadical/src/lrattracer.cpp \
../src/cadical/src/checker.cpp \
../src/cadical/src/internal.cpp \
../src/cadical/src/rephase.cpp \
../src/cadical/src/occs.cpp \
../src/cadical/src/frattracer.cpp \
../src/cadical/src/veripbtracer.cpp \
../src/cadical/src/constrain.cpp \
../src/cadical/src/walk.cpp \
../src/cadical/src/report.cpp \
../src/cadical/src/vivify.cpp \
../src/cadical/src/drattracer.cpp \
../src/cadical/src/decide.cpp \
../src/cadical/src/clause.cpp \
../src/cadical/src/assume.cpp \
../src/cadical/src/stats.cpp \
../src/cadical/src/bins.cpp \
../src/cadical/src/backward.cpp \
../src/cadical/src/watch.cpp \
../src/cadical/src/restart.cpp \
../src/cadical/src/message.cpp \
../src/cadical/src/reap.cpp \
../src/cadical/src/util.cpp \
../src/cadical/src/flags.cpp \
../src/cadical/src/config.cpp \
../src/cadical/src/backtrack.cpp \
../src/cadical/src/profile.cpp \
../src/cadical/src/parse.cpp \
../src/cadical/src/extend.cpp \
../src/cadical/src/block.cpp 

OBJS += \
./src/cadical/src/lookahead.o \
./src/cadical/src/limit.o \
./src/cadical/src/flip.o \
./src/cadical/src/collect.o \
./src/cadical/src/queue.o \
./src/cadical/src/external.o \
./src/cadical/src/shrink.o \
./src/cadical/src/phases.o \
./src/cadical/src/ema.o \
./src/cadical/src/signal.o \
./src/cadical/src/cadical.o \
./src/cadical/src/propagate.o \
./src/cadical/src/logging.o \
./src/cadical/src/compact.o \
./src/cadical/src/cover.o \
./src/cadical/src/decompose.o \
./src/cadical/src/averages.o \
./src/cadical/src/mobical.o \
./src/cadical/src/resources.o \
./src/cadical/src/lratbuilder.o \
./src/cadical/src/file.o \
./src/cadical/src/solution.o \
./src/cadical/src/format.o \
./src/cadical/src/probe.o \
./src/cadical/src/terminal.o \
./src/cadical/src/condition.o \
./src/cadical/src/elim.o \
./src/cadical/src/ternary.o \
./src/cadical/src/gates.o \
./src/cadical/src/restore.o \
./src/cadical/src/lucky.o \
./src/cadical/src/score.o \
./src/cadical/src/external_propagate.o \
./src/cadical/src/idruptracer.o \
./src/cadical/src/ccadical.o \
./src/cadical/src/options.o \
./src/cadical/src/version.o \
./src/cadical/src/subsume.o \
./src/cadical/src/lratchecker.o \
./src/cadical/src/var.o \
./src/cadical/src/analyze.o \
./src/cadical/src/deduplicate.o \
./src/cadical/src/proof.o \
./src/cadical/src/instantiate.o \
./src/cadical/src/transred.o \
./src/cadical/src/minimize.o \
./src/cadical/src/arena.o \
./src/cadical/src/lidruptracer.o \
./src/cadical/src/contract.o \
./src/cadical/src/random.o \
./src/cadical/src/reduce.o \
./src/cadical/src/solver.o \
./src/cadical/src/ipasir.o \
./src/cadical/src/lrattracer.o \
./src/cadical/src/checker.o \
./src/cadical/src/internal.o \
./src/cadical/src/rephase.o \
./src/cadical/src/occs.o \
./src/cadical/src/frattracer.o \
./src/cadical/src/veripbtracer.o \
./src/cadical/src/constrain.o \
./src/cadical/src/walk.o \
./src/cadical/src/report.o \
./src/cadical/src/vivify.o \
./src/cadical/src/drattracer.o \
./src/cadical/src/decide.o \
./src/cadical/src/clause.o \
./src/cadical/src/assume.o \
./src/cadical/src/stats.o \
./src/cadical/src/bins.o \
./src/cadical/src/backward.o \
./src/cadical/src/watch.o \
./src/cadical/src/restart.o \
./src/cadical/src/message.o \
./src/cadical/src/reap.o \
./src/cadical/src/util.o \
./src/cadical/src/flags.o \
./src/cadical/src/config.o \
./src/cadical/src/backtrack.o \
./src/cadical/src/profile.o \
./src/cadical/src/parse.o \
./src/cadical/src/extend.o \
./src/cadical/src/block.o \

CPP_DEPS += \
./src/cadical/src/lookahead.d \
./src/cadical/src/limit.d \
./src/cadical/src/flip.d \
./src/cadical/src/collect.d \
./src/cadical/src/queue.d \
./src/cadical/src/external.d \
./src/cadical/src/shrink.d \
./src/cadical/src/phases.d \
./src/cadical/src/ema.d \
./src/cadical/src/signal.d \
./src/cadical/src/cadical.d \
./src/cadical/src/propagate.d \
./src/cadical/src/logging.d \
./src/cadical/src/compact.d \
./src/cadical/src/cover.d \
./src/cadical/src/decompose.d \
./src/cadical/src/averages.d \
./src/cadical/src/mobical.d \
./src/cadical/src/resources.d \
./src/cadical/src/lratbuilder.d \
./src/cadical/src/file.d \
./src/cadical/src/solution.d \
./src/cadical/src/format.d \
./src/cadical/src/probe.d \
./src/cadical/src/terminal.d \
./src/cadical/src/condition.d \
./src/cadical/src/elim.d \
./src/cadical/src/ternary.d \
./src/cadical/src/gates.d \
./src/cadical/src/restore.d \
./src/cadical/src/lucky.d \
./src/cadical/src/score.d \
./src/cadical/src/external_propagate.d \
./src/cadical/src/idruptracer.d \
./src/cadical/src/ccadical.d \
./src/cadical/src/options.d \
./src/cadical/src/version.d \
./src/cadical/src/subsume.d \
./src/cadical/src/lratchecker.d \
./src/cadical/src/var.d \
./src/cadical/src/analyze.d \
./src/cadical/src/deduplicate.d \
./src/cadical/src/proof.d \
./src/cadical/src/instantiate.d \
./src/cadical/src/transred.d \
./src/cadical/src/minimize.d \
./src/cadical/src/arena.d \
./src/cadical/src/lidruptracer.d \
./src/cadical/src/contract.d \
./src/cadical/src/random.d \
./src/cadical/src/reduce.d \
./src/cadical/src/solver.d \
./src/cadical/src/ipasir.d \
./src/cadical/src/lrattracer.d \
./src/cadical/src/checker.d \
./src/cadical/src/internal.d \
./src/cadical/src/rephase.d \
./src/cadical/src/occs.d \
./src/cadical/src/frattracer.d \
./src/cadical/src/veripbtracer.d \
./src/cadical/src/constrain.d \
./src/cadical/src/walk.d \
./src/cadical/src/report.d \
./src/cadical/src/vivify.d \
./src/cadical/src/drattracer.d \
./src/cadical/src/decide.d \
./src/cadical/src/clause.d \
./src/cadical/src/assume.d \
./src/cadical/src/stats.d \
./src/cadical/src/bins.d \
./src/cadical/src/backward.d \
./src/cadical/src/watch.d \
./src/cadical/src/restart.d \
./src/cadical/src/message.d \
./src/cadical/src/reap.d \
./src/cadical/src/util.d \
./src/cadical/src/flags.d \
./src/cadical/src/config.d \
./src/cadical/src/backtrack.d \
./src/cadical/src/profile.d \
./src/cadical/src/parse.d \
./src/cadical/src/extend.d \
./src/cadical/src/block.d \


# Each subdirectory must supply rules for building sources it contributes
src/cadical/src/%.o: ../src/cadical/src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	clang++ -g -DNDEBUG -DMINISAT_CONSTANTS_AS_MACROS -DNLOGPRECO -DNSTATSPRECO -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I../src/ -I../src/minisat -I../src/kissat/src -I../src/allsat/ -I../src/stlsoft/include -I../src/kissat/src/include -I../src/fastformat/include -I../unittests/gtest -I../unittests/gtest/include -O3 -w -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


